# Generated by Django 2.0.6 on 2018-06-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='Title', max_length=30),
        ),
    ]
